### ISSUE TITLE
css package

### ISSUE THREAD

**Issue by nsaunders** [gbagan/purescript-libraries#1]
I noticed that you list the [css](https://github.com/purescript-contrib/purescript-css) package [here](https://github.com/gbagan/purescript-libraries#css) in the README. About a year ago, [I took over maintainership](https://github.com/purescript-contrib/purescript-css/commit/45b7cd93161e07e3815029529fbc69402ef230d8), but it didn't take me long to realize that it needed a complete overhaul:

1. The library is simply too incomplete for any serious project. Examples: [virtually no pseudo-selectors](https://github.com/purescript-contrib/purescript-css/blob/710d6a742beb88299faf08aaeb997ee1e24483ab/src/CSS/Pseudo.purs), [virtually no support for media queries](https://github.com/purescript-contrib/purescript-css/blob/710d6a742beb88299faf08aaeb997ee1e24483ab/src/CSS/Media.purs), [no grid properties](https://github.com/purescript-contrib/purescript-css/issues/112), and so on.

2. Countless issues with namespacing and keyword reuse. For example, I might have to write a declaration like [`overflow overflowInherit`](https://github.com/purescript-contrib/purescript-css/blob/0484362a4b7df7a783c0b3affbef85d1803a21f8/src/CSS/Overflow.purs#L38-L39) because the [`CSS.Common.inherit`](https://github.com/purescript-contrib/purescript-css/blob/0484362a4b7df7a783c0b3affbef85d1803a21f8/src/CSS/Common.purs#L19) value is incompatible with the `overflow` function/property. Similarly, I would have to [`float floatLeft`](https://github.com/purescript-contrib/purescript-css/blob/975f884c39ddd8d69ad7631e07effef0d639d0ee/src/CSS/Display.purs#L124-L125) or [`textAlign leftTextAlign`](https://github.com/purescript-contrib/purescript-css/blob/f53adac05485315611c31a3aa0dd53cd8e9db0d6/src/CSS/TextAlign.purs#L26-L27).

3. While some type classes exist to support keyword reuse (even if not implemented consistently), they don't solve conflicts between property names and keyword values. For example, `left` is both a value (e.g. `float: left`) and a property (e.g. `left: 100px`). Without fundamental design changes, the only solution is to awkwardly name the functions that represent them and/or require them to be imported (qualified) from separate modules.

4. Not all that much type safety. For example, [`backgroundImage []`](https://github.com/purescript-contrib/purescript-css/blob/2e3883038a574e62c577ed70f2f7e9dd15e482e8/src/CSS/Background.purs#L278-L279) would compile just fine but result in the invalid declaration `background-image: ;`. Similarly, the [`boxShadow` function](https://github.com/purescript-contrib/purescript-css/blob/2e3883038a574e62c577ed70f2f7e9dd15e482e8/src/CSS/Box.purs#L54-L56) accepts any `Size a` values including [percentages](https://github.com/purescript-contrib/purescript-css/blob/56fde10542ca7e506dd2881836e51607106461ef/src/CSS/Size.purs#L79-L81), but actually the `box-shadow` property [doesn't support percentages](https://w3c.github.io/csswg-drafts/css-backgrounds/#typedef-shadow).

5. Not much flexibility. For example, [`boxShadow`](https://github.com/purescript-contrib/purescript-css/blob/2e3883038a574e62c577ed70f2f7e9dd15e482e8/src/CSS/Box.purs#L54-L56) only supports a single shadow, while [the corresponding CSS property allows multiple shadows or `none`](https://w3c.github.io/csswg-drafts/css-backgrounds/#propdef-box-shadow). Less critically, but just as annoyingly, properties like [`padding`](https://github.com/purescript-contrib/purescript-css/blob/5570e04805fb382e5bb4b56420c4cb3f1822edb6/src/CSS/Geometry.purs#L39-L40) require values for all four sides, instead of supporting their [very commonly used shorthand syntax](https://www.w3.org/TR/css-box-3/#propdef-padding).

6. [Producing invalid output](https://github.com/purescript-contrib/purescript-css/issues/165) actually makes static typing counterproductive.

garyb, a previous maintainer and prominent member of the PureScript Core Team, [alluded to problems as far back as 2018](https://discourse.purescript.org/t/css-strategies-for-purescript-apps/374/2). Another core team member acknowledged to me privately that the _css_ package is "quite old" and "not in the best shape". [The earliest committers](https://github.com/purescript-contrib/purescript-css/commits/main?after=710d6a742beb88299faf08aaeb997ee1e24483ab+174&branch=main&qualified_name=refs%2Fheads%2Fmain) are long gone. And I was given sole maintainership after [a single decent PR](https://github.com/purescript-contrib/purescript-css/pull/140#issuecomment-1023569672). I think it's safe to say (although I _am_ sorry to say it) that no one feels much of a sense of ownership over this codebase, and I doubt that anyone familiar believes it's particularly good.

Hopefully, then, you'll understand why I essentially gave up and created a new CSS library called [Tecton](https://github.com/nsaunders/purescript-tecton). I'm not claiming perfection, but I certainly have addressed all of the issues described above and then some. For each feature I've implemented, I've carefully referenced the relevant W3C specifications; and I've heavily leveraged type classes to achieve a flexible API that actually somewhat resembles the underlying CSS. For good measure, I've implemented over 1,700 tests based on real CSS examples from the W3C and MDN and adapted a [sizable real-world example](https://github.com/nsaunders/purescript-tecton/blob/3e161ac3364c89e1470ca0395da74526e0dc1076/examples/ZenGarments.purs) to help ensure adequate CSS coverage.

I do regret that I had to create a new library because many in the PureScript community are unaware of it and newcomers will almost certainly stumble upon the _css_ package first. However, the alternative was to break compatibility in a big way, which I'm not sure everyone would be willing to accept. (On the other hand, this creates a bit of a "namespacing" issue and potential fragmentation in the community, so perhaps there is some possibility of Tecton replacing the _css_ package in the future.)

Anyway, thanks for reading. Please do check out [Tecton](https://github.com/nsaunders/purescript-tecton) and, if you feel it is appropriate, consider replacing the _css_ listing in the README.

**Comment by gbagan** [comment]
Thanks for your advice. I will remove the css library and add Tecton.
